sonar.projectKey=UPT-FAING-EPIS_si784-2026-ii-si784-2026-ii-examen-u1-usherhalanoccarojas
sonar.organization=upt-faing-epis
sonar.projectName=si784-2026-ii-si784-2026-ii-examen-u1-usherhalanoccarojas
sonar.projectVersion=1.0.0

sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests

sonar.exclusions=**/obj/**,**/bin/**,**/dist/**,**/node_modules/**,**/*.spec.ts,**/coverage/**,**/wwwroot/**
sonar.coverage.exclusions=**/Migrations/**,**/Program.cs,**/tests/**

sonar.cs.opencover.reportsPaths=**/TestResults/**/coverage.opencover.xml
sonar.sourceEncoding=UTF-8
